// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  CORS_ORIGIN: 'http: //localhost:3000' | 'https://develop.front-ybj.pages.dev' | 'https://front-ybj.pages.dev/'
}
