// Generated by Wrangler by running `wrangler types -e local --env-interface CloudflareEnv ./src/types/env.d.ts`

interface CloudflareEnv {
  CORS_ORIGIN:
    | "http://localhost:5173/"
    | "https://todo-front-dev.omen-bt.workers.dev"
    | "https://todo-front-prd.omen-bt.workers.dev";
}
